<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Pb;

interface APIService extends \Lv\Grpc\Service
{
    function Stop(\Pb\Empty $request) : \Pb\Empty;
    function CurrentAddress(\Pb\KeySelection $request) : \Pb\Address;
    function NewAddress(\Pb\KeySelection $request) : \Pb\Address;
    function ChainTip(\Pb\CoinSelection $request) : \Pb\Height;
    function Balance(\Pb\CoinSelection $request) : \Pb\Balances;
    function MasterPrivateKey(\Pb\CoinSelection $request) : \Pb\Key;
    function MasterPublicKey(\Pb\CoinSelection $request) : \Pb\Key;
    function HasKey(\Pb\Address $request) : \Pb\BoolResponse;
    function Params(\Pb\Empty $request) : \Pb\NetParams;
    function Transactions(\Pb\CoinSelection $request) : \Pb\TransactionList;
    function GetTransaction(\Pb\Txid $request) : \Pb\Tx;
    function GetFeePerByte(\Pb\FeeLevelSelection $request) : \Pb\FeePerByte;
    function Spend(\Pb\SpendInfo $request) : \Pb\Txid;
    function BumpFee(\Pb\Txid $request) : \Pb\Txid;
    function AddWatchedScript(\Pb\Address $request) : \Pb\Empty;
    function GetConfirmations(\Pb\Txid $request) : \Pb\Confirmations;
    function SweepAddress(\Pb\SweepInfo $request) : \Pb\Txid;
    function CreateMultisigSignature(\Pb\CreateMultisigInfo $request) : \Pb\SignatureList;
    function Multisign(\Pb\MultisignInfo $request) : \Pb\RawTx;
    function EstimateFee(\Pb\EstimateFeeData $request) : \Pb\Fee;
    function GetKey(\Pb\Address $request) : \Pb\Key;
    function ListKeys(\Pb\CoinSelection $request) : \Pb\Keys;
    function ListAddresses(\Pb\CoinSelection $request) : \Pb\Addresses;
    function WalletNotify(\Pb\CoinSelection $request) : \Pb\Tx;
    function DumpTables(\Pb\CoinSelection $request) : \Pb\Row;
}
