<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

/**
 * Protobuf enum <code>Pb\CoinType</code>
 */
class CoinType
{
    /**
     * Generated from protobuf enum <code>BITCOIN = 0;</code>
     */
    const BITCOIN = 0;
    /**
     * Generated from protobuf enum <code>BITCOIN_CASH = 1;</code>
     */
    const BITCOIN_CASH = 1;
    /**
     * Generated from protobuf enum <code>ZCASH = 2;</code>
     */
    const ZCASH = 2;
    /**
     * Generated from protobuf enum <code>LITECOIN = 3;</code>
     */
    const LITECOIN = 3;
}

