<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Txid</code>
 */
class Txid extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.CoinType coin = 1;</code>
     */
    private $coin = 0;
    /**
     * Generated from protobuf field <code>string hash = 2;</code>
     */
    private $hash = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.pb.CoinType coin = 1;</code>
     * @return int
     */
    public function getCoin()
    {
        return $this->coin;
    }

    /**
     * Generated from protobuf field <code>.pb.CoinType coin = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCoin($var)
    {
        GPBUtil::checkEnum($var, \Pb\CoinType::class);
        $this->coin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hash = 2;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>string hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;

        return $this;
    }

}

